[wifi]
WIFI_ENABLE_AUTODETECT=false
WIFI_WB_LINK_CARDS=wlx20e15d2bfa3c
WIFI_WIFI_HOTSPOT_CARD=

[camera]
CAMERA_ENABLE_AUTODETECT=false
CAMERA_N_CAMERAS=0

[network]
NW_ETHERNET_CARD=
NW_MANUAL_FORWARDING_IPS=
NW_FORWARD_TO_LOCALHOST_58XX=true
